### ISSUE TITLE
Loading other models (fishhead, impeller) crashes server

### ISSUE THREAD

**Issue by ian-h-chamberlain** [steptools/StepNCViewer#245] opened 2016-07-07 15:23 UTC
This appears to be caused by a segfault after attempting to load the client:

```
info: CAD.js API Server listening on: 8080
GET / 200 634 - 128.805 ms
GET /v3/nc/state/loop/ 200 29 - 2.603 ms
GET /log 200 1987 - 4.863 ms
Segmentation fault: 11
```

**Comment by ian-h-chamberlain** [comment] 2016-07-07 15:27
Present in 1.2.0 as well

**Comment by funnymanpatrick** [comment] 2016-07-07 18:55
This is caused by the Inspection portion of a stpnc file. By manually removing the inspection workingsteps I was able to get files to load @Sam-son

**Comment by funnymanpatrick** [comment] 2016-07-07 19:53
fixed in StepNode PR 102

**Closed as completed by funnymanpatrick** 2016-07-07 19:53 UTC
Labels: bug
